[params.defaults.modules.toxic_swamp]
  translations = ["id", "ru", "el", "de", "pl", "it"] # Optional, available English translations
  proxies = ["fire-swamp"]
  # proxies = ["custom-proxy", "fire-swamp"]
